clone_depth: 10

environment:
  node_pre_gyp_accessKeyId:
    secure: 7nm7VvyIyBo9FKCCe3EeJfo06ms6mZSvkONjwS78Thw=
  node_pre_gyp_secretAccessKey:
    secure: mLU2PF28c0fKyjSFSSufKr7w/KwHCKQEouWPdJRUzNg6/yRiHc5SEU3BMkHzG18M
  matrix:
    - nodejs_version: "4"
      platform: x64
      msvs_toolset: 12
    - nodejs_version: "4"
      platform: x86
      msvs_toolset: 12
      SKIP_LARGE_BUFFER_TEST: true
    - nodejs_version: "6"
      platform: x64
      msvs_toolset: 12
    - nodejs_version: "6"
      platform: x86
      msvs_toolset: 12
      SKIP_LARGE_BUFFER_TEST: true
    - nodejs_version: "7"
      platform: x64
      msvs_toolset: 12
    - nodejs_version: "7"
      platform: x86
      msvs_toolset: 12
      SKIP_LARGE_BUFFER_TEST: true

matrix:
  fast_finish: true

os: Visual Studio 2015

artifacts:
  - path: 'build\stage\**\*.tar.gz'

install:
  - cmd: SET PUBLISH_BINARY=false
  - cmd: git describe --tags --always HEAD > _git_tag.tmp
  - cmd: SET /p GIT_TAG=<_git_tag.tmp
  - cmd: ECHO "LATEST LOCAL TAG:"
  - cmd: ECHO %GIT_TAG%
  - cmd: ECHO "APPVEYOR REPO BRANCH/TAG:"
  - cmd: ECHO %APPVEYOR_REPO_BRANCH%
  - cmd: DEL _git_tag.tmp
  - cmd: SET COMMIT_MSG="%APPVEYOR_REPO_COMMIT_MESSAGE%"
  - cmd: IF x%APPVEYOR_REPO_BRANCH%==x%GIT_TAG% SET PUBLISH_BINARY=true
  - cmd: IF "%APPVEYOR_REPO_TAG%"=="true" SET PUBLISH_BINARY=true
  - cmd: ECHO "Env Var PUBLISH_BINARY:"
  - cmd: ECHO %PUBLISH_BINARY%
  - git submodule update --init --recursive
  - scripts\build-appveyor.bat

build: OFF
test: OFF
deploy: OFF
